// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyftygaqqjfpxdhwiuzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5ZnR5Z2FxcWpmcHhkaHdpdXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNDgzMjYsImV4cCI6MjA2MzgyNDMyNn0.HezrxMrKakjj1qJlUqudNhnqfgdMJ00-bRzirQraa3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);